### ISSUE TITLE
Release laser_filtering into ROS Noetic?

### ISSUE THREAD

**Issue by sloretz** [DLu/laser_filtering#6]
Would you mind releasing `laser_filtering` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 13 repos need it.

I'm not sure how much work it will need. The [Noetic Migration Guide](http://wiki.ros.org/noetic/Migration) or the [guide about transitioning ROS packages to Python 3](http://wiki.ros.org/UsingPython3/) may be useful.

**Comment by DLu** [comment]
https://github.com/ros/rosdistro/pull/24870
